import './01. landing-navigation.cy'
import './02. auth.cy'
import './03. app-navigation.cy'
import './04. search.cy'
import './05. profile.cy'
import './06. profile-follow.cy'
import './07. onbording.cy'
