import './00.1 landing-navigation.cy'
import './01.1 auth.cy'
import './01.2 app-navigation.cy'
import './02.1 profile.cy'
import './02.2 profile negative api tests.cy'
import './03.1 profile-follow.cy'
import './03.2 following_follower negative api test.cy'
import './04.1 search.cy'
import './04.2 search negative api test.cy'
import './05.1 onbording.cy'
import './05.2 assistant negative api test.cy'
import './06.1 notifications.cy'
import './06.2 notifications negative api test.cy'
