import './00.1 landing-navigation.cy'
import './01.1 auth.cy'
import './01.2 app-navigation.cy'
import './04.1 search.cy'
import './02.1 profile.cy'
import './03.2 profile-follow.cy'
import './03.1 following_follower negative api test.cy'
import './05.2 onbording.cy'
import './06.1 notifications.cy'
