-- -- does not work, requires to declare and return a variable
-- DROP FUNCTION IF EXISTS public.read_group_groups_no_variable(uuid);
-- CREATE OR REPLACE FUNCTION public.read_group_groups_no_variable(group_id uuid)
--     RETURNS authenticated_access.groups
--     LANGUAGE plpgsql
--     SECURITY INVOKER
-- AS
-- $$
-- BEGIN
--     SELECT *
--     FROM
--         authenticated_access.groups
--     WHERE
--         authenticated_access.groups.id = group_id;
-- END
-- $$;
